class Strings {
  static const String bySukant = 'By: Sukant Rajkarnikar';
  static const String appName = 'Furnihome Store';
  static const String home = 'Home';
  static const String searchStore = 'Search Store';
  static const String featuredProducts = 'Featured Products';
  static const String category = 'Category';
  static const String nRs = 'NRs';
  static const String ourNewReleases = 'Our New Releases';
  static const String productsWithArView = 'Products with AR View';
  static const String viewByRoom = 'View By Room';
  static const String livingRoom = 'Living Room';
  static const String bedRoom = 'Bed Room';
  static const String diningRoom = 'Dining Room';
  static const String outdoors = 'Outdoors';
  static const String search = 'Search';
  static const String categories = 'Categories';
  static const String diningTables = 'Dining Tables';
  static const String beds = 'Beds';
  static const String deskChairs = 'Desk Chairs';
  static const String deskTables = 'Desk Tables';
  static const String chairs = 'Chairs';
  static const String sofas = 'Sofas';
  static const String coffeeTables = 'Coffee Tables';
  static const String others = 'Others';
  static const String tryItYourself = 'Try it Yourself';
  static const String rooms = 'Rooms';
  static const String description = 'Description';
  static const String something_went_wrong = 'Something went wrong';
  static const String search_result_for = 'Search Results for:';
  static const String no_data = 'No Data';
  static const String loading_ar_object = 'Loading AR Object';
  static const String moving_object = 'Moving AR Object, use two fingers to rotate';
  static const String rotating_object = 'Rotating AR Object, use one fingers to move';
  static const String place_object_toast = 'Tap on plane where you want to place your object';
  static const String ar_view_unavailable = 'AR View Not Available';
  static const String image_placeholder_url = 'https://firebasestorage.googleapis.com/v0/b/furnihome-production-project.appspot.com/o/placeholder.jpg?alt=media&token=087e4d7a-bb66-4175-82a1-7a1c17955970';
  static const String image_saved = 'Image saved';
  static const String storage_permission_not_granted = 'Storage Permission Not Granted';
  static const String back = 'Back';
  static const String ar_view_info = 'AR View Info';
  static const String no_result_found = 'No Results Found';

}